const en = {
  title: "o7 electronic signature",
  hint: "Prepare a document, place the fields, then send it through your workspace’s Mailing connector.",
  new: "Prepare a document",
  upload: "Import PDF",
  generate: "Create PDF",
  document: "Document title",
  text: "Document content",
  variables: "Document variables",
  recipient: "Signatory",
  name: "Full name",
  email: "Email",
  addRecipient: "Add signatory",
  save: "Save draft",
  send: "Send for signature",
  resend: "Resend invitations",
  cancel: "Cancel request",
  signature: "Signature",
  initials: "Initials",
  date: "Signing date",
  fieldText: "Text",
  fieldType: "Field type",
  place:
    "Choose a field and signatory, then click on the PDF to place it. Drag a field to move it.",
  fields: "Signature fields",
  required: "Required",
  preset: "Prefilled value (optional)",
  remove: "Remove",
  draft: "Draft",
  sent: "Awaiting signatures",
  completed: "Signed",
  void: "Cancelled",
  open: "Open",
  download: "Download signed PDF",
  audit: "Download event record",
  mail: "Mailing connector",
  notConfigured:
    "Configure SMTP/Mailcow and a sender address in Mailing settings before sending. Drafts can already be prepared.",
  configure: "Open Mailing settings",
  empty: "No signature documents yet.",
  busy: "Working…",
  client: "Prefill from a CRM contact",
  none: "Choose a contact",
  type: "Type",
  draw: "Draw",
  clear: "Clear signature",
  consent:
    "I have read the document and agree to sign it electronically using the fields completed above.",
  sign: "Sign document",
  verifyTitle: "Verify your email",
  requestCode: "Email me a verification code",
  code: "Six-digit code",
  verify: "Verify and open document",
  codeSent: "Code sent. Check your mailbox.",
  signed: "Your signature has been recorded.",
  waiting:
    "The remaining signatories still need to sign. You will receive the completed PDF by email.",
  allSigned: "The document has been signed by everyone.",
  verifyHint:
    "The document is available only after verification of the invited email address.",
  back: "Back to documents",
  deliveryFailed: "Some emails failed. Check the connector and resend.",
  mailFailed: "The signed PDF was saved, but some completion emails failed.",
  resendCompleted: "Resend signed PDF",
  selected: "Selected field",
  x: "Left (%)",
  y: "Top (%)",
  width: "Width (%)",
  height: "Height (%)",
  saveFirst: "Save your fields before sending.",
  invalid: "Complete every signatory and place their required signature field.",
  template: "Start from an existing template",
  expires: "Link expires",
  noFields: "Add at least one required signature field for each signatory.",
  downloadOriginal: "Download source PDF",
  status: "Status",
  prepare: "Prepare",
  verification: "Email verified by code",
  password: "No CRM account is required to sign.",
  notSigned: "Not signed",
  mailAccepted: "Email accepted by mail server",
  mailPending: "Email pending",
  mailError: "Email failed",
};
const fr = {
  ...en,
  title: "Signature électronique o7",
  hint: "Préparez le document, placez les champs puis envoyez-le via le connecteur Mailing de votre espace.",
  new: "Préparer un document",
  upload: "Importer un PDF",
  generate: "Créer le PDF",
  document: "Titre du document",
  text: "Contenu du document",
  variables: "Variables du document",
  recipient: "Signataire",
  name: "Nom complet",
  email: "E-mail",
  addRecipient: "Ajouter un signataire",
  save: "Enregistrer le brouillon",
  send: "Envoyer pour signature",
  resend: "Renvoyer les invitations",
  cancel: "Annuler la demande",
  signature: "Signature",
  initials: "Initiales",
  date: "Date de signature",
  fieldText: "Texte",
  fieldType: "Type de champ",
  place:
    "Choisissez un champ et un signataire, puis cliquez sur le PDF pour le placer. Faites glisser un champ pour le déplacer.",
  fields: "Champs à compléter",
  required: "Obligatoire",
  preset: "Valeur préremplie (facultatif)",
  remove: "Supprimer",
  draft: "Brouillon",
  sent: "En attente de signatures",
  completed: "Signé",
  void: "Annulé",
  open: "Ouvrir",
  download: "Télécharger le PDF signé",
  audit: "Télécharger l’historique",
  mail: "Connecteur Mailing",
  notConfigured:
    "Configurez SMTP/Mailcow et une adresse d’expédition dans les paramètres Mailing avant l’envoi. Vous pouvez déjà préparer les brouillons.",
  configure: "Ouvrir les paramètres Mailing",
  empty: "Aucun document à signer pour le moment.",
  busy: "Traitement…",
  client: "Préremplir depuis un contact du CRM",
  none: "Choisir un contact",
  type: "Saisir",
  draw: "Dessiner",
  clear: "Effacer la signature",
  consent:
    "J’ai lu le document et j’accepte de le signer électroniquement avec les champs complétés ci-dessus.",
  sign: "Signer le document",
  verifyTitle: "Vérifiez votre adresse e-mail",
  requestCode: "Recevoir un code par e-mail",
  code: "Code à six chiffres",
  verify: "Vérifier et ouvrir le document",
  codeSent: "Code envoyé. Consultez votre messagerie.",
  signed: "Votre signature a été enregistrée.",
  waiting:
    "Les autres signataires doivent encore signer. Vous recevrez le PDF complet par e-mail.",
  allSigned: "Le document a été signé par tous les destinataires.",
  verifyHint:
    "Le document est accessible après vérification de l’adresse e-mail invitée.",
  back: "Retour aux documents",
  deliveryFailed:
    "Certains mails ont échoué. Vérifiez le connecteur puis renvoyez les invitations.",
  mailFailed:
    "Le PDF signé est enregistré, mais certains mails de confirmation ont échoué.",
  resendCompleted: "Renvoyer le PDF signé",
  selected: "Champ sélectionné",
  x: "Gauche (%)",
  y: "Haut (%)",
  width: "Largeur (%)",
  height: "Hauteur (%)",
  saveFirst: "Enregistrez vos champs avant d’envoyer.",
  invalid:
    "Complétez chaque signataire et placez son champ de signature obligatoire.",
  template: "Partir d’un modèle existant",
  expires: "Expiration du lien",
  noFields: "Ajoutez un champ de signature obligatoire pour chaque signataire.",
  downloadOriginal: "Télécharger le PDF source",
  status: "Statut",
  prepare: "Préparer",
  verification: "E-mail vérifié par code",
  password: "Aucun compte CRM n’est nécessaire pour signer.",
  notSigned: "Non signé",
  mailAccepted: "E-mail accepté par le serveur",
  mailPending: "E-mail en attente",
  mailError: "Échec de l’envoi",
};
const es = {
  ...en,
  title: "Firma electrónica o7",
  hint: "Prepara el documento, coloca los campos y envíalo mediante el conector Mailing de tu espacio.",
  new: "Preparar un documento",
  upload: "Importar PDF",
  generate: "Crear PDF",
  document: "Título del documento",
  text: "Contenido del documento",
  variables: "Variables del documento",
  recipient: "Firmante",
  name: "Nombre completo",
  addRecipient: "Añadir firmante",
  save: "Guardar borrador",
  send: "Enviar para firma",
  resend: "Reenviar invitaciones",
  cancel: "Cancelar solicitud",
  signature: "Firma",
  initials: "Iniciales",
  date: "Fecha de firma",
  fieldText: "Texto",
  fieldType: "Tipo de campo",
  place:
    "Selecciona un campo y un firmante, luego pulsa en el PDF para colocarlo. Arrastra un campo para moverlo.",
  fields: "Campos de firma",
  required: "Obligatorio",
  preset: "Valor prellenado (opcional)",
  remove: "Eliminar",
  draft: "Borrador",
  sent: "Esperando firmas",
  completed: "Firmado",
  void: "Cancelado",
  open: "Abrir",
  download: "Descargar PDF firmado",
  audit: "Descargar historial",
  mail: "Conector Mailing",
  notConfigured:
    "Configura SMTP/Mailcow y una dirección remitente en los parámetros Mailing antes de enviar. Ya puedes preparar borradores.",
  configure: "Abrir parámetros Mailing",
  empty: "Todavía no hay documentos para firmar.",
  busy: "Procesando…",
  client: "Prellenar desde un contacto del CRM",
  none: "Seleccionar contacto",
  type: "Escribir",
  draw: "Dibujar",
  clear: "Borrar firma",
  consent:
    "He leído el documento y acepto firmarlo electrónicamente con los campos completados arriba.",
  sign: "Firmar documento",
  verifyTitle: "Verifica tu correo electrónico",
  requestCode: "Recibir un código por correo",
  code: "Código de seis dígitos",
  verify: "Verificar y abrir documento",
  codeSent: "Código enviado. Revisa tu correo.",
  signed: "Tu firma ha sido registrada.",
  waiting:
    "Los demás firmantes aún deben firmar. Recibirás el PDF completo por correo.",
  allSigned: "Todos los destinatarios han firmado.",
  verifyHint:
    "El documento estará disponible después de verificar el correo invitado.",
  back: "Volver a documentos",
  deliveryFailed:
    "Algunos correos fallaron. Revisa el conector y reenvía las invitaciones.",
  mailFailed:
    "El PDF firmado está guardado, pero algunos correos de confirmación fallaron.",
  resendCompleted: "Reenviar PDF firmado",
  selected: "Campo seleccionado",
  x: "Izquierda (%)",
  y: "Arriba (%)",
  width: "Ancho (%)",
  height: "Alto (%)",
  saveFirst: "Guarda los campos antes de enviar.",
  invalid: "Completa cada firmante y coloca su campo de firma obligatorio.",
  template: "Partir de una plantilla",
  expires: "Caducidad del enlace",
  noFields: "Añade un campo de firma obligatorio para cada firmante.",
  downloadOriginal: "Descargar PDF original",
  status: "Estado",
  prepare: "Preparar",
  verification: "Correo verificado con código",
  password: "No necesitas una cuenta CRM para firmar.",
  notSigned: "Sin firmar",
  mailAccepted: "Correo aceptado por el servidor",
  mailPending: "Correo pendiente",
  mailError: "Correo fallido",
};
export function signatureLabels(language: string) {
  return language === "fr" ? fr : language === "es" ? es : en;
}
