export type SignatureField = {
  id: string;
  page: number;
  x: number;
  y: number;
  width: number;
  height: number;
  type: 'signature' | 'initials' | 'date' | 'text';
  recipientId: string;
  label: string;
  required: boolean;
  preset?: string;
};
export type SignatureValue = { text?: string; image?: string };
export type SignatureRecipient = {
  id: string;
  name: string;
  email: string;
  tokenHash?: string;
  codeHash?: string;
  codeExpires?: number;
  codeAttempts?: number;
  codeRequests?: number[];
  lastCodeAt?: number;
  sessionHash?: string;
  sessionExpires?: number;
  verifiedAt?: string;
  signedAt?: string;
  values?: Record<string, SignatureValue>;
  delivery?: 'PENDING' | 'SENT' | 'FAILED';
  deliveryError?: string;
};
export type SignatureAudit = {
  at: string;
  event: string;
  actor: string;
  ip?: string;
  detail?: string;
  previous: string;
  hash: string;
};
export type SignatureEnvelope = {
  id: string;
  tenantId: string;
  ownerId: string;
  ownerEmail: string;
  tenantName: string;
  title: string;
  status: 'DRAFT' | 'SENT' | 'COMPLETED' | 'VOID';
  createdAt: string;
  sentAt?: string;
  completedAt?: string;
  expiresAt?: number;
  pages: number;
  pageSizes: { width: number; height: number }[];
  originalHash: string;
  signedHash?: string;
  originalFile: string;
  signedFile?: string;
  recipients: SignatureRecipient[];
  fields: SignatureField[];
  audit: SignatureAudit[];
  completionDelivery?: 'SENT' | 'FAILED';
  language: 'fr' | 'es' | 'en';
};
